### ISSUE TITLE
DEV ENVIRONMENT: $gulp run (error)

### ISSUE THREAD

**Issue by oneezy** [handsomecode/trello-parent-child#10]
Forking over a copy so I can work on features #1 and #2, I've ran into a snag. Following the instructions from the [Handsom Wiki](https://github.com/handsomecode/trello-parent-child/wiki), produced a `$ gulp run` error. In particular, it looks like the issues is with the gulp task `firefox-run`. 

Any idea what could be causing the problem?

---
## My Environment:

**OS:** Windows 10 (64-bit)
**Git SCM:** 2.7.0 (MINGW64)
**Node:** 6.3.0
**Gulp:** 3.9.1
## Full output:

```
Oneeezy@Oneezy MINGW64 ~/Desktop/www_/_trello/__trello.extensions/trello-parent-child (master)
$ gulp run
(node:16764) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[09:52:49] Using gulpfile ~\Desktop\www_\_trello\__trello.extensions\trello-parent-child\gulpfile.js
[09:52:49] Starting 'run'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
[09:52:49] Starting 'clean'...
[09:52:49] Finished 'clean' after 58 ms
[09:52:49] Starting 'styles'...
[09:52:49] Starting 'options'...
[09:52:49] Finished 'options' after 121 ms
[09:52:49] Finished 'styles' after 128 ms
[09:52:49] Starting 'firefox'...
[09:52:49] Finished 'firefox' after 47 ms
[09:52:49] Starting 'firefox-run'...
'..' is not recognized as an internal or external command,
operable program or batch file.
[09:52:49] 'firefox-run' errored after 23 ms
[09:52:49] Error in plugin 'gulp-shell'
Message:
    Command failed: cd ./build/firefox && ../../node_modules/.bin/jpm run
'..' is not recognized as an internal or external command,
operable program or batch file.

Details:
    killed: false
    code: 1
    signal: null
    cmd: cd ./build/firefox && ../../node_modules/.bin/jpm run
    stdout:
    stderr: '..' is not recognized as an internal or external command,
operable program or batch file.

[09:52:49] 'run' errored after 260 ms
[09:52:49] Error: [object Object]
    at formatError (C:\Users\Oneeezy\AppData\Roaming\nvm\v6.3.0\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\Oneeezy\AppData\Roaming\nvm\v6.3.0\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\Oneeezy\Desktop\www_\_trello\__trello.extensions\trello-parent-child\node_modules\orchestrator\index.js:264:8)
    at C:\Users\Oneeezy\Desktop\www_\_trello\__trello.extensions\trello-parent-child\node_modules\orchestrator\index.js:275:23
    at finish (C:\Users\Oneeezy\Desktop\www_\_trello\__trello.extensions\trello-parent-child\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (C:\Users\Oneeezy\Desktop\www_\_trello\__trello.extensions\trello-parent-child\node_modules\orchestrator\lib\runTask.js:29:3)
    at finish (C:\Users\Oneeezy\Desktop\www_\_trello\__trello.extensions\trello-parent-child\node_modules\gulp-run-sequence\index.js:35:5)
    at Gulp.onError (C:\Users\Oneeezy\Desktop\www_\_trello\__trello.extensions\trello-parent-child\node_modules\gulp-run-sequence\index.js:41:4)
```

**Comment by danilvalov** [comment]
@oneezy 
Maybe you didn't run `npm install` before?

**Comment by oneezy** [comment]
I ran it @danilvalov , but I'll give it a re-try.

**Comment by alexzub** [comment]
@oneezy Have you had a chance to get further with the build process?

**Comment by alexzub** [comment]
@oneezy I've just ran the process through on a clean installation of an OS X – had no problems, so that must be something with the environment. Windows doesn't recognize a command in there.

Seeing that the task that fails – Firefox Run – is the task that basically launches Firefox, you can get away with just "gulp" if you develop for Chrome, especially since Firefox version isn't even public yet.

Please let me know if you run into any other problems.
